id: A34CE9542
base_file: f0E78.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:10:15.181762
  last_modified_at: 2022-06-11 13:10:15.181770
